### ISSUE TITLE
[2/10 2022 14:21:31]: Error: File is not a zip file

### ISSUE THREAD

**Issue by Omar8345** [Jiusoft/webx#12]
I tried opening the launcher today and I get this error, can you check it @Jothin-kumar @Jiusoft/developers  

Also there is an error in line 194
```py
    t.setDaemon(True)
```

Error:
```
C:\Users\osedk\Downloads\webx-main (1)\webx-main\scripts\webx.py:194: DeprecationWarning: setDaemon() is deprecated, set the daemon attribute instead
  t.setDaemon(True)'Not' is not recognized as an internal or external command,
operable program or batch file.
```

@Jothin-kumar  Check ASAP!

**Comment by Omar8345** [comment]
@Jothin-kumar Can you please fix it then ? Reply from Telegram GitHub Bot

**Comment by Jothin-kumar** [comment]
> @Jothin-kumar we can include both, but src code in inside a special folder ? @orlandohuang what about it ? Reply from GitHub Telegram Bot

That won't solve this issue...

**Comment by Jothin-kumar** [comment]
> @Jothin-kumar then remove that launcher for now to avoid errors

we can directly run `webx/main.py` for now...

**Comment by Jothin-kumar** [comment]
@Omar8345 actually, this issue is because we haven't uploaded a zip file for windows yet! It works fine on linux...

**Comment by Omar8345** [comment]
Oh okie, please fix this issue ASAP for windows, I am thinking to make major changes and updates will change the whole browser by today. Best regards, From: Jothin kumarSent: Saturday, 12 February 2022 6:59 PMTo: Jiusoft/webxCc: Omar; MentionSubject: Re: [Jiusoft/webx] [2/10 2022 14:21:31]: Error: File is not a zip file (Issue ***@***.*** actually, this issue is because we haven't uploaded a zip file for windows yet! It works fine on linux...—Reply to this email directly, view it on GitHub, or unsubscribe.Triage notifications on the go with GitHub Mobile for iOS or Android. You are receiving this because you were mentioned.Message ID: ***@***.***>

**Comment by Omar8345** [comment]
> @Omar8345 actually, this issue is because we haven't uploaded a zip file for windows yet! It works fine on linux...

then, what to do is upload a zip for windows

**Comment by Jothin-kumar** [comment]
> > @Omar8345 actually, this issue is because we haven't uploaded a zip file for windows yet! It works fine on linux...
> 
> then, what to do is upload a zip for windows

Yes

**Comment by Omar8345** [comment]
@Jothin-kumar then, do it

**Comment by Omar8345** [comment]
@Omar8345 lemme know when done

**Comment by orlandohuang** [comment]
I have another plan for windows btw, just (never gonna give you up :rofl: ) lol, just gonna create update mechanism for windows.
